sudo: false

language: node_js

node_js:
    - 10
    - 12
    - 13
    - 14

matrix:
    fast_finish: true

cache:
    directories:
        - node_modules

before_install:
    - npm config set spin false
    - npm config set progress false
    - npm install -g npm

install:
    - npm prune
    - npm update --no-save

script:
    - npm test
    - npm install . -g >/dev/null && npm uninstall . -g >/dev/null
    - mkdir -p "/tmp/$TRAVIS_REPO_SLUG" && cd "/tmp/$TRAVIS_REPO_SLUG" && npm init -y >/dev/null
    - npm install "$TRAVIS_BUILD_DIR" >/dev/null && npm uninstall "$TRAVIS_BUILD_DIR" >/dev/null
    - node -e "const config = require('@$TRAVIS_REPO_SLUG');"
    - cd "$TRAVIS_BUILD_DIR"

deploy:
    - provider: npm
      email: npm@whizark.com
      api_key:
          secure: a2UpGyLmLAtJOvnz26k314zXVyyYPe2lQxW2sy8eGTQ8pT9zkdUEI1+JfiJyZ0IQqn3I4LJXkPasbOXjWHBFODxa5MkjNDLGBua7kmzJSNIxamAYkVaVVNjbJFmoK5LahD7rSkUOJ6xn+RmLBwLZ+gIthd6JlY4k8f2LO1cGuitEiQ8kj6kXdIQsXfBEj68FBN82wr6F4fBQbHiBoxIUOq+jLy/ijfaLSjB8lg/6Wl1yu9LjvCS6X7arNQ6/bojZx6I+s+paFu0rmyY82J6YjKXz0CYc8taLNmdz9aWHVt+X9HBtpjM+7ae2YUj/SCEVOYWsmqMPM6XCNdmSdy5/X10c5KtE/q+Fcoy9txcp9lrCJMJ5VW/MoqfguLDV5RIusFC/tsQoMLtrEE4dJK0+XK9cNSkNlpvMmiH4x1KHYCiGWpiLcckHEcuca+dlKKT13eae8PTcGM8A1NsfHtDt5napcfq/v6scHQf9NXHjRxohDLuhMyP2nDypcDX3Ar9cmSM8sHxt74qo+/u87JXm88EGXQHRvIZiyQhT0bWw1hCokxMO914vb4rl0bDKFrTJWn7A8kaTOwfmdeh3F+a5Q+AcpF538yUDrNkhoBq359qMbwc3wLjfTqy2FkurZcmK7YLS+wmk7vgHuXZSZV3XMSHGpS4gCF+1bpFWjbC3OMU=
      on:
          node: 14
          repo: whizark/eslint-config
          branch: master
          tags: true

notifications:
    email: false

    slack:
        rooms:
            - secure: f8SW1aUKlJ6Gr7TbFQKql4OrxyUy5hYRLhFFg9rCODF4ZNdyZ91JQte3fcmdHbOSyn3UTbQu0OhApEAXYn1TZIGEHpPEt4eECqZ3oEsJtEku8z3QWBgPwnVpHj98NwzXOaqZEHD+prSQQJCqwiLBVtvoQG+bj+GakUrKjb4TmzL2izlfL499XUDR2+k3ZSzTleKRxw6QclAjmPeQmhxsg+Q/WJLYBLcbA737aYqJb+qmB2dHQl1/3D7mO4etb7FdhoBOu7X1WucEqoue4906o9M7PDx+YPVulZumo3ngUwv2smMsX84Z6L+cTcatAK1PRPlaYNCZI36Dq3e7x0/4IQCWSlGVRGP1IX3eBUsYpvVMFuZPGR4EBMh1XFHWoI3yHvteuxKAJTbD7TDoaf14Gq/yAWwSu9jaqeNt4V5HXFiIt5hSjOgICH6I6YeExOHgLrXApYJG8dFUm1ijgB7BG8wKZJKHsPnYIhfhmP2O/9uAv3ZtUT49/NQSZnXUzZR1qqtQf7U1JBXSQsuZVJWnBDrkTsevuExeHkIcqIQp5Khd9Jry5mLbourdnce36HPLkuXHDu+S3bWgJ7LRjGnew8UFY6sswk9eNKWfQ4uHjpcEsOMr/8tIuoJKT3Tl4WzNDT4MlZGHcRD/L/dE0EJgG+NpyHtpvKdHmnkCULlwk3U=
        on_pull_requests: false
        on_start: never
        on_success: never
        on_failure: change
